dos:
	cd dos
	if exist makefile make 
	cd ..

sdl:
	cd sdl
	if exist makefile make
	cd ..

repldump:
	cd repldump
	if exist makefile make
	cd ..

clean:
	cd dos
	if exist makefile make clean
	cd ..
	cd sdl
	if exist makefile make clean
	cd ..
	cd repldump
	if exist makefile make clean
	cd ..
