seg003 segment byte public 'STUNTSC' use16
    extrn sub_19F14:proc
    extrn sub_1A096:proc
    extrn update_frame:proc
    extrn sub_1C302:proc
    extrn skybox_op:proc
    extrn sub_1CB80:proc
    extrn sub_1CBDC:proc
    extrn sub_1D12E:proc
    extrn sub_1D534:proc
    extrn sub_1D5B4:proc
    extrn load_skybox:proc
    extrn unload_skybox:proc
    extrn load_sdgame2_shapes:proc
    extrn sub_1D92A:proc
    extrn setup_intro:proc
    extrn sub_1DEA6:proc
seg003 ends
