seg007 segment byte public 'STUNTSC' use16
    extrn add_audiodriver_timer:proc
    extrn remove_audiodriver_timer:proc
    extrn pad_id:proc
    extrn init_sfx_engine:proc
    extrn sub_26EF4:proc
    extrn audio_function2:proc
    extrn audio_driver_timer:proc
    extrn sub_2712E:proc
    extrn audio_function2_wrap:proc
    extrn sub_27338:proc
    extrn sub_27374:proc
    extrn sub_273B0:proc
    extrn sub_2740B:proc
    extrn sub_27466:proc
seg007 ends
