seg003 segment byte public 'STUNTSC' use16
    extrn sub_19F14:proc
    extrn sub_1A096:proc
    extrn sub_1A0F4:proc
    extrn sub_1C302:proc
    extrn sub_1C474:proc
    extrn sub_1CB80:proc
    extrn sub_1CBDC:proc
    extrn sub_1D12E:proc
    extrn sub_1D534:proc
    extrn sub_1D5B4:proc
    extrn sub_1D7A2:proc
    extrn sub_1D8B4:proc
    extrn sub_1D8D2:proc
    extrn sub_1D92A:proc
    extrn sub_1D93C:proc
    extrn sub_1DEA6:proc
seg003 ends
