seg004 segment byte public 'STUNTSC' use16
    extrn sub_1E1A0:proc
    extrn off_1F750:word
    extrn off_1F87E:word
    extrn sub_1FAE4:proc
    extrn ported_shape3d_load_all_:proc
    extrn ported_shape3d_free_all_:proc
    extrn shape3d_load_car_shapes:proc
    extrn shape3d_free_car_shapes:proc
    extrn sub_204AE:proc
    extrn setup_track:proc
    extrn off_2147C:word
    extrn sub_217CA:proc
    extrn map_terrain_track:proc
seg004 ends
