seg031 segment byte public 'STUNTSC' use16
    extrn load_2dshape_nofatal2:proc
    extrn sub_39E24:proc
    extrn sub_39E4C:proc
    extrn nullsub_1:proc
    extrn nullsub_2:proc
    extrn init_video:proc
    extrn random_wait:proc
    extrn load_palandcursor:proc
    extrn get_0:proc
    extrn ported_mmgr_alloc_resbytes_:proc
    extrn get_res_ofs_diff_scaled:proc
    extrn get_res_size_scaled:proc
seg031 ends
