seg007 segment byte public 'STUNTSC' use16
    extrn add_audiodriver_timer:proc
    extrn sub_26BD5:proc
    extrn sub_26C06:proc
    extrn init_sfx_engine:proc
    extrn sub_26EF4:proc
    extrn sub_26F6D:proc
    extrn sub_2712E:proc
    extrn sub_272F4:proc
    extrn sub_27338:proc
    extrn sub_27374:proc
    extrn sub_273B0:proc
    extrn sub_2740B:proc
    extrn sub_27466:proc
seg007 ends
